import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Give Thanks</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-screen h-screen flex flex-col justify-center items-center mt-[-20px]'>
        <h1 className='text-4xl font-bold mb-10'>Give thanks post video.</h1>

        <div className='max-w-[600px] bg-red-200 h-100'>
          <video src='/giveThanks2022-1.mp4' controls></video>
        </div>
      </main>
    </div>
  );
}
